# Latent Dirichlet Allocation (LDA)

🎯 The goal of this challenge is to find topics within a corpus of emails with the **LDA** algorithm (Unsupervised Learning in NLP)

✉️ Here is a collection of 1K+ ***unlabelled emails***. Let's try to ***extract topics*** from them!

In [1]:
import pandas as pd

url = 'https://wagon-public-datasets.s3.amazonaws.com/05-Machine-Learning/10-Natural-Language-Processing/lda_data'

data = pd.read_csv(url, sep=",", header=None)
data.columns = ['text']
data.head()

                                                text
0  From: gld@cunixb.cc.columbia.edu (Gary L Dare)...
1  From: atterlep@vela.acs.oakland.edu (Cardinal ...
2  From: miner@kuhub.cc.ukans.edu\nSubject: Re: A...
3  From: atterlep@vela.acs.oakland.edu (Cardinal ...
4  From: vzhivov@superior.carleton.ca (Vladimir Z...

In [2]:
data.shape

(1199, 1)

## (1) Preprocessing

❓ **Question (Cleaning**) ❓ You're used to it by now... Clean up! Store the cleaned text in a new column "clean_text" of the DataFrame.

In [ ]:
# YOUR CODE HERE
import string

def clean_text(text):
     text = text.lower()
     text = ''.join(char for char in text if not char.isdigit())
     text = ''.join(char for char in text if char not in string.punctuation)
     text = text.strip()
     return text

data["clean_text"] = data["text"].apply(clean_text)

data.head()

,text,clean_text
0,From: gld@cunixb.cc.columbia.edu (Gary L Dare)...,from gldcunixbcccolumbiaedu gary l dare\nsubje...
1,From: atterlep@vela.acs.oakland.edu (Cardinal ...,from atterlepvelaacsoaklandedu cardinal ximene...
2,From: miner@kuhub.cc.ukans.edu\nSubject: Re: A...,from minerkuhubccukansedu\nsubject re ancient ...
3,From: atterlep@vela.acs.oakland.edu (Cardinal ...,from atterlepvelaacsoaklandedu cardinal ximene...
4,From: vzhivov@superior.carleton.ca (Vladimir Z...,from vzhivovsuperiorcarletonca vladimir zhivov...

## (2) Latent Dirichlet Allocation model

❓ **Question (Training)** ❓ Train a LDA model to extract potential topics

In [4]:
# YOUR CODE HERE
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

vectorizer = CountVectorizer(stop_words='english')
data_vectorized = vectorizer.fit_transform(data['clean_text'])

lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_model.fit(data_vectorized)

LatentDirichletAllocation(n_components=5, random_state=42)

##  (3) Visualize potential topics

🎁 We coded for you a  function that prints the words associated with the potential topics.

In [5]:
def print_topics(model, vectorizer):
    for idx, topic in enumerate(model.components_):
        print("Topic %d:" % (idx))
        print([(vectorizer.get_feature_names_out()[i], topic[i])
                        for i in topic.argsort()[:-10 - 1:-1]])

❓ **Question** ❓ Print the topics extracted by your LDA.

In [6]:
# YOUR CODE HERE
print_topics(lda_model, vectorizer)

Topic 0:
[('subject', 142.77884517625637), ('lines', 137.9575099889634), ('organization', 126.83760884199828), ('university', 90.61946469050542), ('writes', 79.81515791964267), ('mary', 71.55683650181206), ('church', 65.22710591652341), ('think', 63.537049744636604), ('leafs', 55.73292177160024), ('like', 51.51462352895043)]
Topic 1:
[('church', 255.29805724337876), ('god', 234.18966270450318), ('jesus', 202.35144917735178), ('law', 163.57039193851656), ('people', 154.6294935034165), ('subject', 142.8466227937295), ('lines', 132.6265760927634), ('organization', 126.41879788290541), ('does', 122.7237266824272), ('say', 114.29595749024259)]
Topic 2:
[('team', 620.6957735146035), ('hockey', 539.0750545367338), ('game', 476.23577738308427), ('subject', 435.7926828028606), ('lines', 423.69577130163384), ('organization', 418.32512886690296), ('nhl', 360.3698013094303), ('season', 328.5273934117169), ('writes', 310.05454482766174), ('players', 307.7668229138791)]
Topic 3:
[('god', 948.0425048290022), ('people', 579.4114106633031), ('subject', 534.8245452446121), ('lines', 480.68666633422606), ('think', 460.08143014598755), ('organization', 445.11169406122235), ('know', 413.69412427975857), ('dont', 403.1916890356443), ('jesus', 390.31829041889364), ('believe', 389.032469313213)]
Topic 4:
[('period', 240.49494619545533), ('la', 240.28953116896457), ('pts', 217.93891678487), ('vs', 206.13863634776948), ('play', 188.25421019431042), ('power', 148.83655339226755), ('flyers', 137.0135839888283), ('pp', 132.9036655809768), ('chi', 131.1973551457744), ('det', 126.19731412391373)]

## (4) Predict the document-topic mixture of a new text

❓ **Question (Prediction)** ❓

Now that your LDA model is fitted, you can use it to predict the topics of a new text.

1. Vectorize the example
2. Use the LDA on the vectorized example to predict the topics

In [8]:
example = ["My team performed poorly last season. Their best player was out injured and only played one game"]

In [9]:
# YOUR CODE HERE
example_vectorized = vectorizer.transform(example)

topic_mixture = lda_model.transform(example_vectorized)

topic_mixture

array([[0.02001475, 0.02013551, 0.91940221, 0.02010729, 0.02034024]])

🏁 Congratulations! You know how to implement an LDA quickly.

💾 Don't forget to `git add/commit/push` your notebook...

🚀 ... and move on to the next challenge!